attributes = {
    "Upper Body Clothing": [
        {"type": "T-shirt", "color": None},
        {"type": "Shirt", "color": None},
        {"type": "Blouse", "color": None},
        {"type": "Sweater", "color": None},
        {"type": "Jacket", "color": None},
        {"type": "Coat", "color": None},
        {"type": "Hoodie", "color": None},
        {"type": "Blazer", "color": None},
        {"type": "Vest", "color": None},
        {"type": "Tank top", "color": None},
        {"type": "Cardigan", "color": None},
        {"type": "Poncho", "color": None},
        {"type": "Polo", "color": None},
        {"type": "Tunic", "color": None},
        {"type": "Crop top", "color": None},
        {"type": "Bustier", "color": None},
        {"type": "Kimono top", "color": None},
        {"type": "Halter top", "color": None},
        {"type": "Peplum top", "color": None},
        {"type": "Kaftan", "color": None},
        {"type": "Shrug", "color": None}
    ],
    "Lower Body Clothing": [
        {"type": "Pants", "color": None},
        {"type": "Jeans", "color": None},
        {"type": "Trousers", "color": None},
        {"type": "Shorts", "color": None},
        {"type": "Leggings", "color": None},
        {"type": "Skirt", "color": None},
        {"type": "Cargo pants", "color": None},
        {"type": "Capris", "color": None},
        {"type": "Sweatpants", "color": None},
        {"type": "Joggers", "color": None},
        {"type": "Slacks", "color": None},
        {"type": "Culottes", "color": None},
        {"type": "Chinos", "color": None},
        {"type": "Bell-bottoms", "color": None},
        {"type": "Parachute pants", "color": None},
        {"type": "Harem pants", "color": None},
        {"type": "Palazzo pants", "color": None},
        {"type": "Denim shorts", "color": None},
        {"type": "Bermuda shorts", "color": None}
    ],
    "Outerwear": [
        {"type": "Raincoat", "color": None},
        {"type": "Trench coat", "color": None},
        {"type": "Parka", "color": None},
        {"type": "Windbreaker", "color": None},
        {"type": "Overcoat", "color": None},
        {"type": "Poncho", "color": None},
        {"type": "Safari jacket", "color": None},
        {"type": "Pea coat", "color": None},
        {"type": "Duffle coat", "color": None},
        {"type": "Bomber jacket", "color": None},
        {"type": "Leather jacket", "color": None},
        {"type": "Puffer jacket", "color": None},
        {"type": "Gilet", "color": None}
    ],
    "Dresses": [
        {"type": "Dress", "color": None},
        {"type": "Cocktail dress", "color": None},
        {"type": "Ball gown", "color": None},
        {"type": "Suit jacket", "color": None},
        {"type": "Evening gown", "color": None},
        {"type": "Sundress", "color": None},
        {"type": "Wrap dress", "color": None},
        {"type": "Sheath dress", "color": None},
        {"type": "Shirt dress", "color": None},
        {"type": "Mermaid dress", "color": None},
        {"type": "Tunic dress", "color": None},
        {"type": "Off-shoulder dress", "color": None},
        {"type": "Asymmetrical dress", "color": None},
        {"type": "Shift dress", "color": None},
        {"type": "A-line dress", "color": None}
    ],
    "Footwear": [
        {"type": "Shoes", "color": None},
        {"type": "Boots", "color": None},
        {"type": "Sneakers", "color": None},
        {"type": "Sandals", "color": None},
        {"type": "Slippers", "color": None},
        {"type": "Heels", "color": None},
        {"type": "Loafers", "color": None},
        {"type": "Flats", "color": None},
        {"type": "Wedges", "color": None},
        {"type": "Moccasins", "color": None},
        {"type": "Flip-flops", "color": None},
        {"type": "Clogs", "color": None},
        {"type": "Mules", "color": None},
        {"type": "Espadrilles", "color": None},
        {"type": "Ballet flats", "color": None},
        {"type": "Platform shoes", "color": None},
        {"type": "Stilettos", "color": None},
        {"type": "Cowboy boots", "color": None},
        {"type": "Combat boots", "color": None},
        {"type": "Ankle boots", "color": None}
    ],
    "Headwear": [
        {"type": "Hat", "color": None},
        {"type": "Cap", "color": None},
        {"type": "Beanie", "color": None},
        {"type": "Fedora", "color": None},
        {"type": "Beret", "color": None},
        {"type": "Helmet", "color": None},
        {"type": "Headband", "color": None},
        {"type": "Visor", "color": None},
        {"type": "Cloche", "color": None},
        {"type": "Top hat", "color": None},
        {"type": "Boater hat", "color": None},
        {"type": "Bonnet", "color": None},
        {"type": "Bucket hat", "color": None},
        {"type": "Newsboy cap", "color": None},
        {"type": "Flat cap", "color": None},
        {"type": "Fez", "color": None},
        {"type": "Mask", "color": None}
    ],
    "Accessories": [
        {"type": "Belt", "color": None},
        {"type": "Scarf", "color": None},
        {"type": "Gloves", "color": None},
        {"type": "Tie", "color": None},
        {"type": "Bow tie", "color": None},
        {"type": "Suspenders", "color": None},
        {"type": "Watch", "color": None},
        {"type": "Bracelet", "color": None},
        {"type": "Necklace", "color": None},
        {"type": "Earrings", "color": None},
        {"type": "Sunglasses", "color": None},
        {"type": "Handbag", "color": None},
        {"type": "Backpack", "color": None},
        {"type": "Brooch", "color": None},
        {"type": "Cufflinks", "color": None},
        {"type": "Hairpin", "color": None},
        {"type": "Bangle", "color": None},
        {"type": "Ring", "color": None},
        {"type": "Choker", "color": None},
        {"type": "Headscarf", "color": None},
        {"type": "Wristband", "color": None},
        {"type": "Fanny pack", "color": None},
        {"type": "Garter", "color": None},
        {"type": "Socks", "color": None}
    ],
    "Underwear & Lingerie": [
        {"type": "Underwear", "color": None},
        {"type": "Boxers", "color": None},
        {"type": "Briefs", "color": None},
        {"type": "Panties", "color": None},
        {"type": "Bra", "color": None},
        {"type": "Camisole", "color": None},
        {"type": "Corset", "color": None},
        {"type": "Slip", "color": None},
        {"type": "Thong", "color": None},
        {"type": "G-string", "color": None},
        {"type": "Bodysuit", "color": None},
        {"type": "Long johns", "color": None},
        {"type": "Sports briefs", "color": None},
        {"type": "Bralette", "color": None},
        {"type": "Shapewear", "color": None},
        {"type": "Lace bodysuit", "color": None},
        {"type": "Chemise", "color": None},
        {"type": "Nightgown", "color": None},
        {"type": "Pajamas", "color": None},
        {"type": "Lingerie", "color": None}
    ],
    "Athletic Wear": [
        {"type": "Tracksuit", "color": None},
        {"type": "Sports bra", "color": None},
        {"type": "Biker shorts", "color": None},
        {"type": "Athletic shorts", "color": None},
        {"type": "Yoga pants", "color": None},
        {"type": "Running shoes", "color": None},
        {"type": "Jersey", "color": None},
        {"type": "Swim trunks", "color": None},
        {"type": "Rash guard", "color": None},
        {"type": "Warm-up jacket", "color": None},
        {"type": "Tennis skirt", "color": None},
        {"type": "Cycling jersey", "color": None}
    ],
    "Specialty Clothing": [
        {"type": "Suit", "color": None},
        {"type": "Tuxedo", "color": None},
        {"type": "Gown", "color": None},
        {"type": "Uniform", "color": None},
        {"type": "Kimono", "color": None},
        {"type": "Robe", "color": None},
        {"type": "Swimsuit", "color": None},
        {"type": "Coveralls", "color": None},
        {"type": "Apron", "color": None},
        {"type": "Cape", "color": None},
        {"type": "Lab coat", "color": None},
        {"type": "Overalls", "color": None},
        {"type": "Sarong", "color": None},
        {"type": "Lehenga", "color": None},
        {"type": "Sari", "color": None},
        {"type": "Hijab", "color": None},
        {"type": "Abayas", "color": None},
        {"type": "Cheongsam", "color": None},
        {"type": "Dashiki", "color": None},
        {"type": "Academic gown", "color": None},
        {"type": "Military uniform", "color": None},
        {"type": "Wetsuit", "color": None},
        {"type": "Costume", "color": None},
        {"type": "Hakama", "color": None}
    ],
    "Footwear Accessories": [
        {"type": "Shoelaces", "color": None},
        {"type": "Stockings", "color": None},
        {"type": "Tights", "color": None},
        {"type": "Insoles", "color": None},
        {"type": "Shoehorn", "color": None},
        {"type": "Shoe polish", "color": None},
        {"type": "Leg warmers", "color": None},
        {"type": "Foot pads", "color": None},
        {"type": "Boot liners", "color": None},
        {"type": "Gaiters", "color": None}
    ],
    "Gender and Age": [
        {"type": "Male", "color": None},
        {"type": "Female", "color": None},
        {"type": "Non-binary", "color": None},
        {"type": "Genderqueer", "color": None},
        {"type": "Transgender", "color": None},
        {"type": "Agender", "color": None},
        {"type": "Genderfluid", "color": None},
        {"type": "Bigender", "color": None},
        {"type": "Two-spirit", "color": None},
        {"type": "Boy", "color": None},
        {"type": "Girl", "color": None},
        {"type": "Man", "color": None},
        {"type": "Woman", "color": None},
        {"type": "Child", "color": None},
        {"type": "Adult", "color": None},
        {"type": "Senior", "color": None},
        {"type": "Gentleman", "color": None},
        {"type": "Lady", "color": None},
        {"type": "Baby", "color": None},
        {"type": "Kid", "color": None},
        {"type": "Teenager", "color": None},
        {"type": "Elder", "color": None},
        {"type": "Old person", "color": None}
    ]
}