import cv2
import torch

from load_model import model, processor


def florence2(task_prompt, image, text_input=None):
    """
    Generate text based on the provided task prompt and input image.

    Parameters:
    - task_prompt (str): The prompt specifying the task.
    - image (PIL.Image): The input image.
    - text_input (str, optional): Additional text input to append to the task prompt.

    Returns:
    - parsed_answer: The processed answer generated by the model.
    """
    # Construct the prompt
    prompt = task_prompt if text_input is None else task_prompt + text_input
    
    # Prepare inputs for the model
    inputs = processor(text=prompt, images=image, return_tensors="pt")
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Generate output from the model
    generated_ids = model.generate(
        input_ids=inputs["input_ids"].to(DEVICE),  # Move to the specified device
        pixel_values=inputs["pixel_values"].to(DEVICE),  # Move to the specified device
        max_new_tokens=1024,
        early_stopping=False,
        do_sample=False,
        num_beams=3,
    )

    # Decode the generated text
    generated_text = processor.batch_decode(generated_ids, skip_special_tokens=False)[0]

    # Post-process the generated text
    parsed_answer = processor.post_process_generation(
        generated_text,
        task=task_prompt,
        image_size=(image.width, image.height)
    )

    return parsed_answer


def get_boxes_by_label(data, label):
    """
    Extracts bounding boxes (bboxes) for a specific label from the input data.

    Parameters:
    - data (dict): A dictionary containing object detection data with 'labels' and 'bboxes' keys.
    - label (str): The label for which bounding boxes are to be extracted.

    Returns:
    - boxs (list): A list of bounding boxes corresponding to the given label.
    """
    boxs = []
    
    # Iterate through all labels and bboxes
    for i, lbl in enumerate(data['<OD>']['labels']):
        if lbl == label:
            bbox = data['<OD>']['bboxes'][i]
            boxs.append(bbox)
    
    return boxs


def draw_boxes(image, boxes, color=(0, 255, 0), thickness=2):
    """
    Draws bounding boxes on the given image.

    Parameters:
    - image (ndarray): The input image on which boxes are to be drawn.
    - boxes (list): A list of bounding boxes, where each box is represented as [x1, y1, x2, y2].
    - color (tuple): The color of the box in (B, G, R) format (default is green).
    - thickness (int): The thickness of the box lines (default is 2).

    Returns:
    - image (ndarray): The image with the bounding boxes drawn on it.
    """
    for box in boxes:
        start_point = (int(box[0]), int(box[1]))  # Top-left corner
        end_point = (int(box[2]), int(box[3]))    # Bottom-right corner
        # Draw the rectangle on the image
        image = cv2.rectangle(image, start_point, end_point, color, thickness)
    
    return image


def process_frame_tasks(frame_rgb, pil_image, frame_count, path_img_out):
    # Generate caption using florence2 function
    task_prompt = '<CAPTION>'
    results = florence2(task_prompt, pil_image)

    # Object detection using florence2 function
    task_prompt_detect = '<OD>'
    result_detect = florence2(task_prompt_detect, pil_image)

    # Find object box
    label_obj = "person"
    obj_box = get_boxes_by_label(result_detect, label_obj)
    print(len(obj_box))
    draw_frame = draw_boxes(frame_rgb,box)
    if len(obj_box) > 0:
        img_crops = []
        for i, box in enumerate(obj_box):
            
            # Crop objects
            crop_area = (int(box[0]), int(box[1]), int(box[2]), int(box[3]))
            crop = pil_image.crop(crop_area)

            task_prompt1 = '<DETAILED_CAPTION>'
            result1 = florence2(task_prompt1, crop)

            # Save cropped image
            image_filename = f"{path_img_out}{frame_count}_{i}.jpg"
            crop.save(image_filename)

            # Save caption to a text file
            caption_filename = f"{path_img_out}{frame_count}_{i}.txt"
            with open(caption_filename, 'w') as file:
                file.write(result1['<DETAILED_CAPTION>'])
            print(f"Đã xong người thứ {i}")

    # Save caption of the whole frame to a text file
    caption_filename = f"{path_img_out}{frame_count}.txt"
    with open(caption_filename, 'w') as file:
        file.write(results['<CAPTION>'])

    # Save the original frame (BGR format)
    image_filename = f"{path_img_out}{frame_count}.jpg"
    cv2.imwrite(image_filename, frame_rgb)
    print(f"Đã lưu ảnh và caption của frame {frame_count}")
    return draw_frame,